[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "e93293f02182c0e585f94ca5fd876213d4731018"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "8e4fced5859cdf01f3897833c07da240e2dec92a71c8ce45b74d9820b9fc87c1"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.1+0/HelloCxx.v0.0.1.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "9db4e9529243e52099863e75c7196f150c6d89c8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "4b39e53a8b85eca884051e399ed35e39bb8efb48c3f34720b8ed2495cb63e3cd"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.1+0/HelloCxx.v0.0.1.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "d5856f3f27ba4e28355dda62b501c8cc969a177b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "6ce358b076b3ab643d69b94bd4777d8c6210045cf5e11202d27a456bc1ada1d6"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.2+0/HelloCxx.v0.0.2.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "1eb40e8ec398134051c5299f56c977babd50e920"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "fc0cfa0efdf4243221405397466e12a875396f80fd3481aa0b1adaeb228e16ea"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.2+0/HelloCxx.v0.0.2.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "bef0cf9e92ffd8d37631970bd183476bf03c9764"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "eb71027645465e5e6f7cfddf88d495c2efd20b9b82ea1bfde6f900f13bb3af37"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.3+0/HelloCxx.v0.0.3.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[HelloCxx]]
arch = "x86_64"
git-tree-sha1 = "56c1dc7630207332d44c5cac09a5f514fed7d888"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[HelloCxx.download]]
    sha256 = "32c5bb5662a4321e1c939c974be71b7f7be195faaa3e3f0f55a60e7046ade859"
    url = "https://github.com/j-fu/HelloCxx_jll.jl/releases/download/HelloCxx-v0.0.3+0/HelloCxx.v0.0.3.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
