# Autogenerated wrapper script for HelloCxx_jll for x86_64-linux-gnu-julia_version+1.9.0
export libHelloCxx

using libcxxwrap_julia_jll
using libjulia_jll
JLLWrappers.@generate_wrapper_header("HelloCxx")
JLLWrappers.@declare_library_product(libHelloCxx, "libHelloCxx.so.0")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, libjulia_jll)
    JLLWrappers.@init_library_product(
        libHelloCxx,
        "lib/libHelloCxx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
